language: java

install: true

os: osx
jdk: openjdk11

before_install:
 - chmod +x gradlew

script:
 - ./gradlew build

 before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Thykof"
  - git config --local user.email "thykof@protonmail.ch"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
 provider: releases
 api_key: "15a956aab0d9642e387fcfbe4ec136377461a40f"
 file: "build/libs/hellofxfourth.jar"
 skip_cleanup: true

before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
 directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
